<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Line Coding Virtual Laboratory</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/plotly.js/2.26.0/plotly.min.js"></script>
  <link rel="stylesheet" href="styles.css">
<link href="https://fonts.cdnfonts.com/css/beyonders" rel="stylesheet">
<link href="https://fonts.cdnfonts.com/css/texturina" rel="stylesheet">               
<link href="https://fonts.cdnfonts.com/css/dasher" rel="stylesheet">                                
<link href="https://fonts.cdnfonts.com/css/noto-serif-hebrew" rel="stylesheet">
<link href="https://fonts.cdnfonts.com/css/rajdhani" rel="stylesheet">
                
         
</head>
<body>
  <div class="header">
    <div class="matrix-bg"></div>
    <h1>Line Coding Schemes - Virtual Laboratory</h1>
    <div class="logo">
  <img src="https://ptuniv.edu.in/assets/images/ptu-logo.png" alt="PTU Logo">
</div>

  </div>

  <div class="nav-bar">
    <a href="#" data-page="aim" class="active">Aim</a>
    <a href="#" data-page="theory">Theory</a>
    <a href="#" data-page="procedure">Procedure</a>
    <a href="#" data-page="pretest">Pretest</a>
    <a href="#" data-page="simulation">Simulation</a>
    <a href="#" data-page="posttest">PostTest</a>
    <a href="#" data-page="results">Results</a>
  </div>

  <div class="container">

    <!-- Aim Page -->
    <div class="page active" id="aim">
      <div class="content-section">
        <h2>Aim of the Experiment</h2>
        <p>To study and analyze various line coding schemes used in digital communication systems including:</p>
        <ul>
          <li>Unipolar NRZ (Non-Return to Zero)</li>
          <li>Unipolar RZ (Return to Zero)</li>
          <li>Polar NRZ</li>
          <li>Polar RZ</li>
          <li>Bipolar AMI (Alternate Mark Inversion)</li>
          <li>Pseudo Ternary Encoding</li>
          <li>Manchester Encoding</li>
          <li>HDB3 (High Density Bipolar of order 3)</li>
          <li>B8ZS (Bipolar with 8-Zero Substitution)</li>
        </ul>
        <p>The experiment aims to help students:</p>
        <ul>
          <li>Understand the characteristics and properties of different line coding techniques</li>
          <li>Visualize the waveforms generated by each encoding scheme</li>
          <li>Compare advantages and disadvantages of various line coding methods</li>
          <li>Learn practical applications of line coding in digital communication systems</li>
        </ul>
      </div>
    </div>

    <!-- Theory Page -->
    <div class="page" id="theory">
      <div class="content-section">
        <h2>Theory</h2>
        
        <h3>Introduction to Line Coding</h3>
        <p><strong>Line Coding</strong> is the process of converting digital data (binary sequences of 0s and 1s) into digital signals suitable for transmission over a communication channel. The choice of line coding scheme affects bandwidth requirements, synchronization capability, error detection, and DC component of the signal.We need line coding techniques because raw digital data cannot be sent directly; it must be shaped into a suitable signal. Line coding ensures reliable transmission, maintains synchronization between the transmitter and receiver, reduces errors and noise, optimizes bandwidth usage, and in some cases even supports error detection. All these factors make digital communication accurate and robust.
        </p>
        <h3>Classification of Line Coding Schemes</h3>
        
        <h3>1. Unipolar NRZ (Non-Return to Zero)</h3>
        <p>In Unipolar NRZ, the signal uses only one polarity (positive voltage). Logic 1 is represented by a positive voltage (+V), and logic 0 is represented by zero voltage (0V). The signal does not return to zero between consecutive bits.</p>
        <p><strong>Characteristics:</strong></p>
        <ul>
          <li>Simple implementation</li>
          <li>Presence of DC component</li>
          <li>No self-synchronization capability</li>
          <li>Baseline wander problem for long sequences of 0s or 1s</li>
        </ul>
        
        <h3>2. Unipolar RZ (Return to Zero)</h3>
        <p>Similar to Unipolar NRZ, but the signal returns to zero in the middle of each bit period. Logic 1 is represented by +V for the first half and 0V for the second half. Logic 0 remains at 0V throughout.</p>
        <p><strong>Characteristics:</strong></p>
        <ul>
          <li>Better synchronization than NRZ due to transitions</li>
          <li>Requires more bandwidth (twice that of NRZ)</li>
          <li>Still has DC component issues</li>
        </ul>
        
        <h3>3. Polar NRZ</h3>
        <p>Uses both positive and negative voltage levels. Logic 1 is represented by +V and logic 0 by -V. This is more efficient than unipolar schemes.</p>
        <p><strong>Characteristics:</strong></p>
        <ul>
          <li>Better noise immunity than unipolar</li>
          <li>No DC component for balanced data</li>
          <li>More power efficient</li>
          <li>Synchronization issues for long runs of same bit</li>
        </ul>
        
        <h3>4. Polar RZ</h3>
        <p>Combines the advantages of polar signaling with return-to-zero. Signal returns to zero in the middle of each bit period.</p>
        <p><strong>Characteristics:</strong></p>
        <ul>
          <li>Better synchronization than Polar NRZ</li>
          <li>Requires twice the bandwidth</li>
          <li>Good noise immunity</li>
        </ul>
        
        <h3>5. Bipolar AMI (Alternate Mark Inversion)</h3>
        <p>Logic 0 is represented by zero voltage. Logic 1 alternates between +V and -V. Consecutive 1s have opposite polarity.</p>
        <p><strong>Characteristics:</strong></p>
        <ul>
          <li>No DC component</li>
          <li>Simple error detection (violation of alternation rule)</li>
          <li>Better bandwidth utilization</li>
          <li>Problem with long sequences of zeros</li>
        </ul>

        <h3>6. Pseudo Ternary</h3>
        <p>Pseudo Ternary is a modified encoding scheme where the roles of 1s and 0s are reversed compared to AMI. Binary 1 is represented by 0V (zero voltage), while binary 0 alternates between positive voltage (+V) and negative voltage (-V).</p>
        <p><strong>Logic:</strong></p>
        <ul>
          <li><strong>Binary 1:</strong> 0V (No pulse)</li>
          <li><strong>Binary 0:</strong> Alternates between +V and -V</li>
        </ul>
        <p><strong>Characteristics:</strong></p>
        <ul>
          <li>Uses three voltage levels (+V, 0V, -V)</li>
          <li>No DC component for balanced data</li>
          <li>Good for long sequences of 1s (represented as no pulse)</li>
          <li>Better synchronization for data with many 0s</li>
          <li>Inverse representation of Bipolar AMI</li>
        </ul>

        <h3>7. Manchester Encoding</h3>
        <p>Also known as bi-phase encoding. Logic 1 is represented by a transition from low to high in the middle of the bit period. Logic 0 is represented by a transition from high to low.</p>
        <p><strong>Characteristics:</strong></p>
        <ul>
          <li>Excellent self-synchronization (transition in every bit)</li>
          <li>No DC component</li>
          <li>Used in Ethernet (10BASE-T)</li>
          <li>Requires twice the bandwidth</li>
        </ul>
        
        <h3>8. HDB3 (High Density Bipolar of order 3)</h3>
        <p>An improvement over AMI that prevents long sequences of zeros. When four consecutive zeros occur, they are replaced by a special code that includes a violation (same polarity as previous 1).</p>
        <p><strong>Characteristics:</strong></p>
        <ul>
          <li>Solves the long zero sequence problem of AMI</li>
          <li>Maintains synchronization</li>
          <li>No DC component</li>
          <li>Used in E1 carrier systems</li>
          <li>Case 1: Even number of pulses since last violation → use B00V</li>
          <li>Case 2: Odd number of pulses since last violation → use 000V</li>
        </ul>
        
        <h3>9. B8ZS (Bipolar with 8-Zero Substitution)</h3>
        <p>A line coding method used mainly in North America to solve the problem of long sequences of zeros in AMI. When eight consecutive zeros (00000000) occur, they are replaced with a special pattern <strong>000VB0BV</strong> (appearing inside the 8-zero block), where <strong>V</strong> represents a bipolar violation and <strong>B</strong> represents a balancing pulse.</p>
        <p><strong>Substitution Pattern:</strong></p>
        <p>The 8 zeros <strong>00000000</strong> are replaced with:  
        <strong>000VB0BV</strong><br>
        • <strong>B</strong> = Balancing pulse (same polarity as expected alternate pulse)<br>
        • <strong>V</strong> = Violation pulse (same polarity as previous pulse)</p>

        <p><strong>Characteristics:</strong></p>
        <ul>
          <li>Replaces long sequences of 8 zeros</li>
          <li>The pattern 000VB0BV maintains synchronization</li>
          <li>Has no DC component</li>
          <li>Widely used in T1 carrier systems</li>
        </ul>
      </div>
    </div>

    <!-- Procedure Page -->
    <div class="page" id="procedure">
      <div class="content-section">
        <h2>Procedure</h2>
        
        <h3>Step 1: Understanding the Block Diagram</h3>
        <p>Navigate to the Home page to see the interactive block diagram showing the flow from Input Signal → Line Encoder → Virtual Oscilloscope. You can drag blocks and create connections between them.</p>
        
        <h3>Step 2: Access the Simulation</h3>
        <p>Click on the "Simulation" tab in the navigation bar to access the virtual oscilloscope interface.</p>
        
        <h3>Step 3: Enter Binary Input</h3>
        <p>In the "Binary Input" field, enter your desired binary sequence. For example: <strong>10110100</strong></p>
        <p>Ensure you only use 0s and 1s. The default sequence is already provided for testing.</p>
        
        <h3>Step 4: Generate the Signal</h3>
        <p>Click the "Generate" button to process your input and display it on the oscilloscope.</p>
        
        <h3>Step 5: Select Line Coding Scheme</h3>
        <p>Use the channel selector buttons to switch between different line coding schemes:</p>
        <ul>
          <li><strong>Input:</strong> Shows only the original digital input signal</li>
          <li><strong>Unipolar NRZ:</strong> View unipolar non-return-to-zero encoding</li>
          <li><strong>Unipolar RZ:</strong> View unipolar return-to-zero encoding</li>
          <li><strong>Polar NRZ:</strong> View polar non-return-to-zero encoding</li>
          <li><strong>Polar RZ:</strong> View polar return-to-zero encoding</li>
          <li><strong>Bipolar AMI:</strong> View alternate mark inversion encoding</li>
          <li><strong>Manchester:</strong> View Manchester encoding</li>
          <li><strong>HDB3:</strong> View HDB3 encoding</li>
          <li><strong>Pseudo Ternary:</strong> View pseudo ternary encoding</li>
        </ul>
        
        <h3>Step 6: Adjust Control Parameters</h3>
        <p>Use the two control dials to manipulate the display:</p>
        <ol>
          <li><strong>Bit Rate:</strong> Click and drag the dial to control how many bits are displayed on the screen (4 to 32 bits). The input pattern repeats to fill the screen.</li>
          <li><strong>Amplitude:</strong> Click and drag the dial to adjust the voltage level of the encoded signal (1V to 10V). Note: Input signal amplitude remains constant at 5V.</li>
        </ol>
        
        <h3>Step 7: Observe and Compare</h3>
        <p>Compare the characteristics of different encoding schemes by switching between channels. Notice:</p>
        <ul>
          <li>How each scheme represents the same binary data differently</li>
          <li>The number of voltage levels used</li>
          <li>The presence or absence of transitions</li>
          <li>The bandwidth requirements (RZ and Manchester use more transitions)</li>
        </ul>
        
        <h3>Step 8: Use Oscilloscope Tools</h3>
        <p>The oscilloscope display includes professional tools in the top-right corner:</p>
        <ul>
          <li>Download the plot as PNG image</li>
          <li>Zoom in/out to examine details</li>
          <li>Pan across the waveform</li>
          <li>Autoscale to fit the display</li>
          <li>Reset axes to default view</li>
        </ul>
        
        <h3>Step 9: Record Observations</h3>
        <p>Navigate to the "Results" page to document your findings and observations for each line coding scheme.</p>
      </div>
    </div>

    <!-- Pre-Test Page -->
    <div class="page" id="pretest">
      <div class="content-section">
        <h2>📘 Pre-Test (Before Simulation)</h2>
        <div id="pretestContent"></div>
        <button class="quiz-btn" onclick="submitTest('pretest')">Submit Pre-Test</button>
        <div id="pretestScore" style="margin-top:20px; font-weight:bold; color:#ffb347;"></div>
      </div>
    </div>

    <!-- Simulation Page -->
    <div class="page" id="simulation">
     <div class="block-diagram">
        <h2>Interactive Block Diagram</h2>
        <div class="diagram-container" id="diagramContainer">
          <svg id="connectionSvg" style="position: absolute; width: 100%; height: 100%; pointer-events: none; z-index: 1;">
            <defs>
              <marker id="arrowhead" markerWidth="10" markerHeight="10" refX="9" refY="3" orient="auto">
                <polygon points="0 0, 10 3, 0 6" fill="#ff9966" />
              </marker>
            </defs>
          </svg>
          <div class="diagram-block" data-id="input" style="left: 50px; top: 170px;">
            Input Signal
            <div class="connection-point output" data-block="input" data-type="output"></div>
          </div>
          <div class="diagram-block" data-id="encoder" style="left: 350px; top: 170px;">
            Line Encoder
            <div class="connection-point input" data-block="encoder" data-type="input"></div>
            <div class="connection-point output" data-block="encoder" data-type="output"></div>
          </div>
          <div class="diagram-block" data-id="oscilloscope" style="left: 700px; top: 170px;">
            Virtual Oscilloscope
            <div class="connection-point input" data-block="oscilloscope" data-type="input"></div>
          </div>
          <div class="diagram-block" data-id="psd" style="left: 950px; top: 170px;">
            Power Spectral Density
            <div class="connection-point input" data-block="psd" data-type="input"></div>
          </div>
        </div>
        <div class="controls-info">
          <p><strong>Instructions:</strong></p>
          <p>• Drag blocks to reposition them</p>
          <p>• Click and drag from orange output points (right) to input points (left) to create arrows</p>
          <p>• Click on arrows to delete them</p>
          <p>• Use the reset button to restore default positions and clear connections</p>
          <p>• For HDB3 and B8ZS input more number of zeros</p>
        </div>
        <button class="reset-btn" onclick="resetDiagram()">Reset Diagram</button>
      </div>
      <div class="oscilloscope">
        <div class="scope-header">
          <div class="input-section">
            <label for="binaryInput">Binary Input:</label>
            <input type="text" id="binaryInput" placeholder="Enter binary (e.g., 10110100)" value="10110100">
            <button class="channel-btn" onclick="updateSignal()">Generate</button>
          </div>
          <div class="channel-selector">
            <button class="channel-btn active" onclick="selectChannel(0)">Input</button>
            <button class="channel-btn" onclick="selectChannel(1)">Unipolar NRZ</button>
            <button class="channel-btn" onclick="selectChannel(2)">Unipolar RZ</button>
            <button class="channel-btn" onclick="selectChannel(3)">Polar NRZ</button>
            <button class="channel-btn" onclick="selectChannel(4)">Polar RZ</button>
            <button class="channel-btn" onclick="selectChannel(5)">Bipolar AMI</button>
            <button class="channel-btn" onclick="selectChannel(6)">Pseudo Ternary</button>
            <button class="channel-btn" onclick="selectChannel(7)">Manchester</button>
            <button class="channel-btn" onclick="selectChannel(8)">HDB3</button>
            <button class="channel-btn" onclick="selectChannel(9)">B8ZS</button>
            <button class="channel-btn" id="compareBtn" onclick="enterCompareMode()">COMPARE</button>
            
          </div>
          <!-- Compare controls (hidden until COMPARE pressed) -->
          <div id="compareControls" style="display:none; width:100%; margin-top:12px; gap:10px; align-items:center;">
            <label style="color:#3d3d8c; margin-right:8px; font-weight:bold;">Compare:</label>
            <select id="compareSelectA" class="compare-select" onchange="drawOscilloscope()">
              <option value="1">Unipolar NRZ</option>
              <option value="2">Unipolar RZ</option>
              <option value="3">Polar NRZ</option>
              <option value="4">Polar RZ</option>
              <option value="5">Bipolar AMI</option>
              <option value="6">Pseudo Ternary</option>
              <option value="7">Manchester</option>
              <option value="8">HDB3</option>
              <option value="9">B8ZS</option>
            </select>

            <span style="color:#fff; font-weight:bold; margin:0 6px;">vs</span>

            <select id="compareSelectB" class="compare-select" onchange="drawOscilloscope()">
              <option value="1">Unipolar NRZ</option>
              <option value="2">Unipolar RZ</option>
              <option value="3">Polar NRZ</option>
              <option value="4">Polar RZ</option>
              <option value="5">Bipolar AMI</option>
              <option value="6">Pseudo Ternary</option>
              <option value="7">Manchester</option>
              <option value="8">HDB3</option>
              <option value="9">B8ZS</option>
            </select>

            <button class="channel-btn" onclick="showCompare()" style="margin-left:8px;">Show Compare</button>
            <button class="channel-btn" onclick="closeCompare()" style="background:#aa2d2d;">Close</button>
          </div>
        </div>

        <div class="scope-display">
          <div id="oscilloscope"></div>
        </div>
        <!-- PSD section (hidden until PSD block is connected) -->
        <div id="psdSection" style="display:none; margin-top: 30px;">

          <h2 style="color:white; text-align:center; margin-bottom:20px;">
            Power Spectral Density Analysis
          </h2>

          <div style="display:flex; gap:20px; justify-content:center;">

            <!-- LEFT: THEORETICAL PSD -->
            <div style="width:48%; background:#111; padding:15px; border-radius:10px;">
              <h3 style="color:#4ec9ff; text-align:center;">Theoretical PSD</h3>
              <div id="theoryPSD"></div>
            </div>

            <!-- RIGHT: PRACTICAL PSD -->
            <div style="width:48%; background:#111; padding:15px; border-radius:10px;">
              <h3 style="color:#ffcc66; text-align:center;">Practical PSD (FFT)</h3>
              <div id="practicalPSD"></div>
            </div>

          </div>

        </div>

 
        <div class="controls-section">
          <div class="control-group">
            <h3>Bit Rate (bits shown)</h3>
            <div class="dial-container">
              <svg class="dial-svg" viewBox="0 0 200 200" id="bitRateDial">
                <circle cx="100" cy="100" r="90" fill="none" stroke="#4a90e2" stroke-width="3"/>
                <circle cx="100" cy="100" r="80" fill="url(#dialGradient)" stroke="#2d2d6c" stroke-width="2"/>
                <circle cx="100" cy="100" r="65" fill="#0f0f17" stroke="#3d3d8c" stroke-width="2"/>
                <line x1="100" y1="25" x2="100" y2="35" stroke="#888" stroke-width="2"/>
                <line x1="190" y1="100" x2="180" y2="100" stroke="#888" stroke-width="2"/>
                <line x1="10" y1="100" x2="20" y2="100" stroke="#888" stroke-width="2"/>
                <line x1="156" y1="44" x2="149" y2="51" stroke="#666" stroke-width="1.5"/>
                <line x1="44" y1="44" x2="51" y2="51" stroke="#666" stroke-width="1.5"/>
                <line id="bitRatePointer" x1="100" y1="100" x2="100" y2="35" stroke="#ff9966" stroke-width="5" stroke-linecap="round" filter="url(#glow)"/>
                <circle cx="100" cy="100" r="12" fill="#ff6600" stroke="#ff9966" stroke-width="2"/>
                <text x="54" y="145" text-anchor="middle" fill="#ddd" font-size="14" font-weight="bold">4</text>
                <text x="35" y="108" text-anchor="middle" fill="#ddd" font-size="14" font-weight="bold">8</text>
                <text x="45" y="65" text-anchor="middle" fill="#ddd" font-size="14" font-weight="bold">12</text>
                <text x="78" y="38" text-anchor="middle" fill="#ddd" font-size="14" font-weight="bold">16</text>
                <text x="120" y="38" text-anchor="middle" fill="#ddd" font-size="14" font-weight="bold">20</text>
                <text x="155" y="65" text-anchor="middle" fill="#ddd" font-size="14" font-weight="bold">24</text>
                <text x="164" y="107" text-anchor="middle" fill="#ddd" font-size="14" font-weight="bold">28</text>
                <text x="145" y="145" text-anchor="middle" fill="#ddd" font-size="14" font-weight="bold">32</text>
                <text x="100" y="165" text-anchor="middle" fill="#ddd" font-size="14" font-weight="bold">0</text>
                <defs>
                  <linearGradient id="dialGradient" x1="0%" y1="0%" x2="0%" y2="100%">
                    <stop offset="0%" style="stop-color:#2d2d6c;stop-opacity:1" />
                    <stop offset="100%" style="stop-color:#1a1a4a;stop-opacity:1" />
                  </linearGradient>
                  <filter id="glow">
                    <feGaussianBlur stdDeviation="2" result="coloredBlur"/>
                    <feMerge>
                      <feMergeNode in="coloredBlur"/>
                      <feMergeNode in="SourceGraphic"/>
                    </feMerge>
                  </filter>
                </defs>
              </svg>
              <div class="value-display" id="bitRateValue">8 bits</div>
            </div>
          </div>

          <div class="control-group">
            <h3>Amplitude</h3>
            <div class="dial-container">
              <svg class="dial-svg" viewBox="0 0 200 200" id="amplitudeDial">
                <circle cx="100" cy="100" r="90" fill="none" stroke="#4a90e2" stroke-width="3"/>
                <circle cx="100" cy="100" r="80" fill="url(#dialGradient2)" stroke="#2d2d6c" stroke-width="2"/>
                <circle cx="100" cy="100" r="65" fill="#0f0f17" stroke="#3d3d8c" stroke-width="2"/>
                <line x1="100" y1="25" x2="100" y2="35" stroke="#888" stroke-width="2"/>
                <line x1="190" y1="100" x2="180" y2="100" stroke="#888" stroke-width="2"/>
                <line x1="10" y1="100" x2="20" y2="100" stroke="#888" stroke-width="2"/>
                <line x1="156" y1="44" x2="149" y2="51" stroke="#666" stroke-width="1.5"/>
                <line x1="44" y1="44" x2="51" y2="51" stroke="#666" stroke-width="1.5"/>
                <line id="amplitudePointer" x1="100" y1="100" x2="100" y2="35" stroke="#ff9966" stroke-width="5" stroke-linecap="round" filter="url(#glow2)"/>
                <circle cx="100" cy="100" r="12" fill="#ff6600" stroke="#ff9966" stroke-width="2"/>
                <text x="100" y="175" text-anchor="middle" fill="#ddd" font-size="14" font-weight="bold">0V</text>
                <text x="54" y="145" text-anchor="middle" fill="#ddd" font-size="14" font-weight="bold">1V</text>
                <text x="37" y="116" text-anchor="middle" fill="#ddd" font-size="14" font-weight="bold">2V</text>
                <text x="37" y="83" text-anchor="middle" fill="#ddd" font-size="14" font-weight="bold">3V</text>
                <text x="54" y="54" text-anchor="middle" fill="#ddd" font-size="14" font-weight="bold">4V</text>
                <text x="83" y="37" text-anchor="middle" fill="#ddd" font-size="14" font-weight="bold">5V</text>
                <text x="116" y="37" text-anchor="middle" fill="#ddd" font-size="14" font-weight="bold">6V</text>
                <text x="145" y="54" text-anchor="middle" fill="#ddd" font-size="14" font-weight="bold">7V</text>
                <text x="162" y="83" text-anchor="middle" fill="#ddd" font-size="14" font-weight="bold">8V</text>
                <text x="162" y="116" text-anchor="middle" fill="#ddd" font-size="14" font-weight="bold">9V</text>
                <text x="145" y="145" text-anchor="middle" fill="#ddd" font-size="14" font-weight="bold">10V</text>
                <defs>
                  <linearGradient id="dialGradient2" x1="0%" y1="0%" x2="0%" y2="100%">
                    <stop offset="0%" style="stop-color:#2d2d6c;stop-opacity:1" />
                    <stop offset="100%" style="stop-color:#1a1a4a;stop-opacity:1" />
                  </linearGradient>
                  <filter id="glow2">
                    <feGaussianBlur stdDeviation="2" result="coloredBlur"/>
                    <feMerge>
                      <feMergeNode in="coloredBlur"/>
                      <feMergeNode in="SourceGraphic"/>
                    </feMerge>
                  </filter>
                </defs>
              </svg>
              <div class="value-display" id="amplitudeValue">5.0 V</div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Post-Test Page -->
    <div class="page" id="posttest">
      <div class="content-section">
        <h2>📗 Post-Test (After Simulation)</h2>
        <div id="posttestContent"></div>
        <button class="quiz-btn" onclick="submitTest('posttest')">Submit Post-Test</button>
        <div id="posttestScore" style="margin-top:20px; font-weight:bold; color:#ffb347;"></div>
      </div>
    </div>

    <!-- Results Page -->
    <div class="page" id="results">
      <div class="content-section">
        <h2>Results and Observations</h2>
        
        <h3>Observations for Each Line Coding Scheme</h3>
        
        <h3>1. Unipolar NRZ</h3>
        <p><strong>Voltage Levels Used:</strong> 0V and +V</p>
        <p><strong>Observations:</strong></p>
        <ul>
          <li>Uses only positive voltage levels</li>
          <li>Simple implementation</li>
          <li>Presence of DC component</li>
          <li>No synchronization for long sequences of same bit</li>
        </ul>
        
        <h3>2. Unipolar RZ</h3>
        <p><strong>Voltage Levels Used:</strong> 0V and +V (returns to 0)</p>
        <p><strong>Observations:</strong></p>
        <ul>
          <li>Signal returns to zero in middle of bit period</li>
          <li>Better synchronization than NRZ</li>
          <li>Requires double bandwidth</li>
        </ul>
        
        <h3>3. Polar NRZ</h3>
        <p><strong>Voltage Levels Used:</strong> +V and -V</p>
        <p><strong>Observations:</strong></p>
        <ul>
          <li>Uses both positive and negative voltages</li>
          <li>Better noise immunity than unipolar</li>
          <li>No DC component for balanced data</li>
          <li>More power efficient</li>
        </ul>
        
        <h3>4. Polar RZ</h3>
        <p><strong>Voltage Levels Used:</strong> +V, 0V, and -V</p>
        <p><strong>Observations:</strong></p>
        <ul>
          <li>Returns to zero between bits</li>
          <li>Good synchronization capability</li>
          <li>Higher bandwidth requirement</li>
        </ul>
        
        <h3>5. Bipolar AMI</h3>
        <p><strong>Voltage Levels Used:</strong> +V, 0V, and -V (alternating for 1s)</p>
        <p><strong>Observations:</strong></p>
        <ul>
          <li>Logic 1s alternate between positive and negative</li>
          <li>No DC component</li>
          <li>Simple error detection capability</li>
          <li>Problem with long sequences of zeros</li>
        </ul>

        <h3>6. Pseudo Ternary</h3>
        <p><strong>Voltage Levels Used:</strong> +V, 0V, and -V (alternating for 1s)</p>
        <p><strong>Observations:</strong></p>
        <ul>
          <li>Logic 0s alternate between positive and negative</li>
          <li>Logic 1s are represented by 0V (no pulse)</li>
          <li>No DC component</li>
          <li>Similar to AMI, but 1s and 0s are swapped</li>
          <li>Used where 1s occur more frequently than 0s</li>
        </ul>
        
        <h3>7. Manchester Encoding</h3>
        <p><strong>Voltage Levels Used:</strong> +V and -V (with mid-bit transitions)</p>
        <p><strong>Observations:</strong></p>
        <ul>
          <li>Transition in middle of every bit period</li>
          <li>Excellent self-synchronization</li>
          <li>No DC component</li>
          <li>Requires double bandwidth</li>
          <li>Used in Ethernet networks</li>
        </ul>
        <h3>
        <h3>8. HDB3</h3>
        <p><strong>Voltage Levels Used:</strong> +V, 0V, and -V (with violation codes)</p>
        <p><strong>Observations:</strong></p>
        <ul>
          <li>Prevents long sequences of zeros</li>
          <li>Uses violation codes for four consecutive zeros</li>
          <li>Maintains synchronization</li>
          <li>No DC component</li>
          <li>Used in E1 telecommunication systems</li>
        </ul>
        
        <h3>9. B8ZS</h3>
        <p><strong>Voltage Levels Used:</strong> +V, 0V, and -V (with substitution codes)</p>
        <p>Special substitution 000VB0BV when 8 zeros occur</p>
        <p><strong>Observations:</strong></p>
        <ul>
          <li>Substitutes eight consecutive zeros with a special pattern</li>
          <li>Maintains synchronization</li>
          <li>No DC component</li>
          <li>Introduces B (balancing pulse) and V (violation pulse)</li>
        </ul>
        <h3>Conclusion</h3>
        <p>Successfully studied and analyzed various line coding schemes. Each scheme has its own advantages and applications in digital communication systems. The choice of line coding depends on factors like bandwidth availability, synchronization requirements, DC component tolerance, and error detection needs.</p>
      </div>
    </div>
  </div>

  <footer class="footer">
    <div class="footer-content">
      <h3>Contributors-(PTUstudents)</h3>
      <div class="contributors-list">
        <div class="contributor">
          <strong>Kishore.M</strong> - <a href="spmanikishore1@gmail.com">kishore@example.com</a>
        </div>
        <div class="contributor">
          <strong>Ajay krishna.K</strong> - <a href="spmanisrikrishnakousik@gmail.com">srikrishnakousik@gmail.com</a>
        </div>
        <div class="contributor">
          <strong>Chanthiramouli</strong> - <a href="spmanichanthiramouli15@gmail.com">chanthiramouli15@gmail.com</a>
        </div>
        <div class="contributor">
          <strong>Ganesh.P</strong> - <a href="spmaniganesh.pgvs@gmail.com">ganesh.pgvs@gmail.com</a>
        </div>
        <div class="contributor">
          <strong>Anil Sri</strong> - <a href="spmanianilsrik2@gmail.com">anilsrik2@gmail.com</a>
        </div>
        <div class="contributor">
          <strong>Kumaraguru.V</strong> - <a href="spmani2301109058@ptuniv.edu.in">2301109058@ptuniv.edu.in</a>
        </div>
        <div class="contributor">
          <strong>Harish</strong> - <a href="spmani2301109036@ptuniv.edu.in">2301109036@ptuniv.edu.in</a>
        </div>
        <div class="contributor">
          <strong>Harshik Naidu</strong> - <a href="spmani2301109034@ptuniv.edu.in">2301109034@ptuniv.edu.in</a>
        </div>
        <div class="contributor">
          <strong>Balakumaran</strong> - <a href="spmani2301109015@ptuniv.edu.in">2301109015@ptuniv.edu.in</a>
        </div>
      </div>
      <p class="copyright">&copy; 2025 Line Coding Virtual Laboratory. All rights reserved.</p>
    </div>
  </footer>

  <script src="script.js"></script>
</body>
</html>
